apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/observability-kube-prometheus-stack.yaml
  - manifests/shared-logging-loki.yaml
  - manifests/shared-logging-alloy.yaml