apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ar-image-pull-secret
  namespace: dev-apps
  labels:
    homelab.io/environment: dev
    homelab.io/component: registry
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-sm-dev
  target:
    name: ar-image-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "us-central1-docker.pkg.dev": {
                "username": "_json_key_base64",
                "password": "{{ .sa_key | b64enc }}"
              }
            }
          }
  data:
    - secretKey: sa_key
      remoteRef:
        key: homelab-ar-reader-sa-key
