name: CI/CD - myapp
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Ambiente alvo: dev ou prd"
        required: true
        type: choice
        options:
          - dev
          - prd
        default: dev

jobs:
  build-and-deploy:
    uses: ./.github/workflows/docker-build-push.yaml
    with:
      app-name: myapp
      environment: ${{ inputs.environment }}
      dockerfile: clusters/homelab/workloads/dev/manifests/myapp/Dockerfile
      context: clusters/homelab/workloads/dev/manifests/myapp
    secrets:
      GCP_WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GITOPS_PAT: ${{ secrets.GITOPS_PAT }}
